main/urls.py
from django.contrib import admin
from django.urls import path, include
from news_etis import views

urlpatterns = [
    # path('', views.index, name ='index'),
    path('admin/', admin.site.urls),
    path('news/', include('news_etis.urls')),
    path('registration/',include('news_etis.urls')), 
]

news_etis/urls.py
from django.urls import path, include
from .views import index, index_view

app_name='news_etis'

urlpatterns = [
    path('etis/', index, name='main'),
    path('pass/', index_view, name='index'),
]
        

news_etis/models.py
from django.db import models
from PIL import Image

# Create your models here.

class Profile(models.Model):
    login = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=20)
    

    def __str__(self):
        return self.login


class News(models.Model):
    image = models.ImageField()
    name = models.CharField(max_length=255)
    discription = models.CharField(max_length=255)


    def __str__(self):
        return self.name

news_etis/forms.py
from django import forms
from .models import Profile, News
from newsapi import NewsApiClient
from django.shortcuts import redirect
from django.shortcuts import render
from django.http import HttpResponse


class ProfileForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = Profile
        fields = ('login', 'password')
        
    def clean(self):
        cleaned_data = super(ProfileForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )
        if len(password) <= 8:
            raise forms.ValidationError(
                "password too short"
            )


class NewsForm(forms.ModelForm):
    newsapi = NewsApiClient(api_key ='581afaeacaac42dea128bdf256215c87')
    top = newsapi.get_top_headlines(language='ru', country='ru')

    l = top['articles']
    dsc =[]
    nws =[]
    im =[]

    for i in range(len(l)):
      f = l[i]
      nws.append(f['title'])
      dsc.append(f['description'])
      im.append(f['urlToImage'])
      mylist = zip(nws, dsc, im)

    # return render(request, 'index.html', context ={"mylist":mylist})

news_etis/views.py
from django.shortcuts import render
from django.http import HttpResponse
from newsapi import NewsApiClient
from .models import Profile, News
from .forms import ProfileForm, NewsForm
from .utils import password_validation
from django.shortcuts import redirect


# Create your views here.

def index(request):
    form = NewsForm(request.GET)

    return render(
        request,
        'index.html',
        {'form': form}
    )


def index_view(request):
    message = None
    form = ProfileForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('news_etis:main')
        
    
    return render(
        request,
        'login.html', 
        {'form': form}
    )
    

news_etis/templates/index.html
<!DOCTYPE html>
<html lang="ru" dir="ltr">
<head>
  <meta charset="utf-8">
  <title></title>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!-- Optional theme -->
</head>
<body>
  <div class="jumbotron" style="color:black">

  <h1 style ="color:rgb(253, 0, 0)">
  Последние новости дня 
  <button type="button">
    <a href="{% url 'news_etis:index' %}">Регистрация</a>
  </button>

  </h1>

  </div>


  <div class="container">
  {% for new, des, i in mylist %}
      <img src="{{ i }}" alt="">
      <h1>Новость:</h1> {{ new }}
      {{ value|linebreaks }}

      <h4>Описание:</h4>{{ des }}
      {{ value|linebreaks }}

  {% endfor %}
  </div>

</body>
</html>

news_etis/templates/login.html
<!DOCTYPE html>   
<html>   
<head>  
<meta name="viewport" content="width=device-width, initial-scale=1">  
<title> Login Page </title> 
<style>   
    Body {  
      font-family: Calibri, Helvetica, sans-serif;  
      background-color: white;  
    }  
    button {   
           background-color: #f8f8f8;       
           width: 100%;  
            color: orange;   
            padding: 15px;   
            margin: 10px 0px;   
            border: none;   
            cursor: pointer;   
             }   
     form {   
            border: 3px solid #f1f1f1;   
        }   
     input[type=text], input[type=password] {   
            width: 100%;   
            margin: 8px 0;  
            padding: 12px 20px;   
            display: inline-block;   
            border: 2px solid goldenrod;   
            box-sizing: border-box;   
        }  
     button:hover {   
            opacity: 0.7;   
        }   
      .cancelbtn {   
            width: auto;   
            padding: 10px 18px;  
            margin: 10px 5px;  
        }   
            
         
     .container {   
            padding: 25px;   
            background-color: palegreen;  
        } 
</style> 
</head>    
<body>    
    <center> <h1> {{ category.name }} </h1> </center>
    <center> <h1> {{ result }} </h1> </center> 
    <form method="post"> 
        {% csrf_token %}
        
        <div class="container">   
            {{ form.as_p }}
            <input style="background-color: beige" type='submit' value='Сохранить'>
        </div>   
    </form>     
</body>     
</html>  